name: random_reader
description: Generate random paragraphes from text files.
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  path: ^1.8.0
  file_picker: ^6.1.1
  multi_split_view: ^2.4.0
  shared_preferences: ^2.2.2
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/books/

